### ISSUE TITLE
example data files

### ISSUE THREAD

**Issue by shubhamsaini** [DReichLab/AdmixTools#10]
The example data files seems to be moved. Can you please fix the link.
https://genetics.med.harvard.edu/reich/Reich_Lab/Software_files/AdmixTools_Example_Data.tar.gz

**Comment by mathii** [comment]
Fixed. New link: https://reich.hms.harvard.edu/sites/reich.hms.harvard.edu/files/inline-files/AdmixTools_Example_Data.tar_.gz

**Comment by bumblenick** [comment]
You will find the data on
https://reich.hms.harvard.edu/sites/reich.hms.harvard.edu/
files/inline-files/AdmixTools_Example_Data.tar_.gz

Nick
