### ISSUE TITLE
examples/qpWave.log is missing

### ISSUE THREAD

**Issue by batelz** [DReichLab/AdmixTools#101]
the qpWave [README ](https://github.com/DReichLab/AdmixTools/blob/master/README.QpWave
)refers to a log file called examples/qpWave.log or examples/qpAdm.log with annotations explaining the output.

This file is not located in the examples directory.
Can you please add it?

Thanks,
B.

**Comment by MatthewMah** [comment]
Example log files were set to gitignore and have been added in ed1d8579c550253ac748c7a81e625a7eec88fef0.
