### ISSUE TITLE
how to convert `v54.1.p1_1240K_public.snp` to aligned fasta format data?

### ISSUE THREAD

**Issue by liamxg** [DReichLab/AdmixTools#104]
Dear @MatthewMah,

Could I know how to convert `v54.1.p1_1240K_public.snp` to aligned fasta format data?
Thanks.

**Comment by MatthewMah** [comment]
A SNP file is a series of positions. You take sequencing data and examine it at those positions. There is no sequencing data inherent in the SNP file. 

If you want aligned sequencing data, that sounds like you want Sequence Alignment/Map (SAM/BAM/CRAM).

**Comment by MatthewMah** [comment]
Then you need to start with sequencing data, not a SNP file.
