### ISSUE TITLE
Compilation and installation errors of 8.0.0 on RHEL9

### ISSUE THREAD

**Issue by rattei** [DReichLab/AdmixTools#106]
Hello, build and install of AdmixTools 8.0.0 do not work on a standard RHEL system. The code and CFLAGS are incompatible with GCC 11 and the Makefile tries to install files from pysrc, which does not exist.

To get the software installed, I had to patch the Makefile:
`sed -i "s/-Wimplicit/-Wimplicit -fcommon/" Makefile`
`sed -i "/pysrc/d" Makefile`

Would be great if new releases could be tested on typical platforms before they are releases. We are happy to test on RHEL in the future, if you wish.

best,
Thomas

**Comment by MatthewMah** [comment]
This should be resolved in de6d9ee79bc551295c89fd03a529b3257613150a and 950152c03604ad9601679cdc6d7e7038c4ea3ad1. Let me know if these work for you and I will build a new release.

**Comment by rattei** [comment]
Yes, I can confirm that the last checkout compiles without problems on RHEL9. Thanks for fixing the issue.
