### ISSUE TITLE
Compilation error: cannot overwrite non-directory

### ISSUE THREAD

**Issue by elcortegano** [DReichLab/AdmixTools#107]
I have downloaded the repository in a machine with Ubuntu 20.04 and I am following the instructions to compile AdmixTools.

The steps I am following are:

    cd src/
    make clobber
    sudo make install

This returns a strange error directing to a non-existent folder (above the root directory), and looks like it could be a problem resolving paths in the Makefile.

> ...
mkdir -p  /admixtables
echo "tables made"  > tables
cp twtable  /admixtables
mkdir -p ../bin
cp qp3Pop qpDstat qpF4ratio qpAdm qpWave qp4diff dowtjack qpBound qpGraph qpreroot qpff3base qpDpart qpfstats qpfmv  qpmix  ../bin
cp rexpfit.r  wtjack.pl  ../bin
cp convertf mergeit snpunion simpjack2 grabpars  easystats easycheck easylite  multimerge geno_single transpose merge_transpose ../bin
cp convertf mergeit snpunion simpjack2 grabpars  easystats easycheck easylite  multimerge geno_single transpose merge_transpose ../bin
cp ../perlsrc/* ../bin
cp fxtract /../bin
cp -r script /../bin
cp: cannot overwrite non-directory '/../bin/script' with directory 'script'
make: *** [Makefile:125: install] Error 1

**Comment by MatthewMah** [comment]
The make install command collects the binaries in a directory "bin" and scripts in a subdirectory "script". It's designed to all be local to the project directory, so you do not need sudo. Are you running make from within the src directory?

**Comment by elcortegano** [comment]
Not sure what changed, but I just cloned again the repo and copy pasted the commands to compile and worked. Not sure at this point why if failed before. Sorry for the trouble.
