### ISSUE TITLE
Error with modelling 

### ISSUE THREAD

**Issue by Maroc2567** [DReichLab/AdmixTools#108]
I am trying to model my son in a Neolithic model, first issue I get is having a refusal of a ppnb or natufian source, so I decided to stick without it. What I don’t
 understand in this run is that the second line passes without an Iranian source but when I remove it to make another run it fails? I don’t understand how it passes when the Iranian source is added and he doesn’t score it but it i remove it all together it fails

**Comment by Maroc2567** [comment]
![Uploading IMG_9236.png…]()

**Comment by bumblenick** [comment]
This sort of technical query is not appropriate for github.
Please email me direct.

Nick

**Comment by Maroc2567** [comment]
Hi, I am trying to model my son in a Neolithic model, first issue I get is having a refusal of a ppnb or natufian source, so I decided to stick without it. What I don’t
understand in this run is that the second line passes without an Iranian source but when I remove it to make another run it fails? I don’t understand how it passes when the Iranian source is added and he doesn’t score it but it i remove it all together it fails

I’m just a little confused as to why when an Iranian source is added the second line passes with him scoring 0 percent, then if I remove it the model fails all together.

Kind regards
________________________________

**Comment by Maroc2567** [comment]
@bumblenick what’s your email I don’t have it
