### ISSUE TITLE
genetic position in .snp file

### ISSUE THREAD

**Issue by shubhamsaini** [DReichLab/AdmixTools#11]
I am working with VCF files. I am able to convert between different formats (VCF <--> PLINK <--> EIGENSTRAT). But the .snp file generated in this process has genetic position values all 0. Is there any way I can populate these? Perhaps using the genetic maps files?

**Comment by bumblenick** [comment]
1) 0 is OK in my software and programs like convertf fill in a distance
table using physical position
(1 morgan = 100M bases).  In my own work I have software to fill in
distance with the Oxford map,
but this code is not released.

Thus most software will run OK but for careful work you should find a way
to fill in the table.
Nick

**Comment by shubhamsaini** [comment]
So I'm working with ROLLOFF. I believe most analysis depend on genetic positions and bins sizes in cM. How do you think my analysis would be affected if I were to use genetic position values approximated from the physical positions?

**Comment by bumblenick** [comment]
I've had good luck with doing that, but you ought to use a genetic map if
possible.  What is your genotype array?  By the way, look into ALDER.
Similar math and much faster.

N
