### ISSUE TITLE
qp3Pop report no data for many population groups

### ISSUE THREAD

**Issue by biozzq** [DReichLab/AdmixTools#13]
Hi all,

I want to do three-population admixture test, but when I specified the parameters (in eigenstrat format, which can be used to run `qpDstat` smoothly)  and run `qp3Pop`, the results are all no data. I do not know why. Hope your help!

Thanks
Best
Zhuqing

**Comment by bumblenick** [comment]
Hard to debug with so little info.
Make a list of a few populations (say 6) and run smartpca (poplistname:) to
see if smartpca
has data.
Populations with one sample only and no hets cannot be used for qp3Pop.
Check very carefully your population names both in the .ind file and in
popfilename:
This is usually the problem

Nick

**Comment by biozzq** [comment]
Hi @bumblenick 

Thanks, sorry for the little info. Yes, I have checked the full file with running `smartpca`, it is ok.  And the population names should be ok because `qpDstat` can run with these files smoothly. I have forgotten to show that some population combinations have results but the results are strange (the column of SNPs is very small ), like following
![image](https://cloud.githubusercontent.com/assets/15704257/21740400/1ccaefb8-d4f4-11e6-94b4-1ed59a018196.png)

**Comment by bumblenick** [comment]
OK; This is almost certainly a data problem at your end.
Is your data very thin;   The #SNPs (last column) is just the
number of SNPs where you have valids in all 3 pops and it's not
monomorphic.


You have a l lot of SNPs here.  Too many?, but this is unlikely to be the
problem
I would next make a file with just Agarli Europe Mongolia
(use convertf) and look directly for SNPs that are not monomorphic.
Also look at F_st from smartpca.  Sensible?

Nick

**Comment by biozzq** [comment]
Hi @bumblenick 

Thanks for your help. Maybe something wrong with the format of my input data (I can not find the details of the matter). It runs smoothly now. 

Best
Zhuqing
