### ISSUE TITLE
consistent results between High density SNPs and thinned SNPs

### ISSUE THREAD

**Issue by biozzq** [DReichLab/AdmixTools#14]
Hi @bumblenick 

I want to know whether the thinning process is necessary before running `admixtools` when using high density SNPs. I just care about the accurate of the results.
I have run `F3`, `F4` and `D-statistics` using about 40M SNPs without pruning and 13M SNPs with pruning by LD. When running with 40M SNPs, it also runs fast, and the result is almost consistent with the thinned SNPs. So I want to know, If I just want to run above statistics for a small number of population, can I get a more reasonable result when using all SNPs?

Best
Zhuqing

**Comment by bumblenick** [comment]
On human data 1M SNPs is adequate for nearly all pop gen data.
In my experience thinning makes little difference and in all cases
the standard errors are meaningful,  In your case I would I think thin
down to 1M snps and not worry too much.

Exception:  You have  very large number of samples and want to study
very rare alleles;   then things may be  different.

Nick
