### ISSUE TITLE
Outgroup choosing for Outgroup F3 Statistics

### ISSUE THREAD

**Issue by hssKK** [DReichLab/AdmixTools#19]
Hi,
I have a ancient goat sample and want to know which modern goat group it most close to by using Outgroup F3 Statistics.But my outgroup had a long divergence time with them,so the F3_result is greater than 1.Does it may have some effect to my judge?Is my ancient goat most close to the  modern goat group with the max F3_result?
Thanks!

**Comment by bumblenick** [comment]
Please send me your output (logfile).  And if the ancient sample is a
target you
need diploid calls or more than one sample.

Nick

**Comment by biozzq** [comment]
Dear @bumblenick 

Outgroup-f3 test can be used to measure the shared genetic drift between two test populations.  The f3 result is closely related to the selected outgroup. If the selected outgroup is far away from the test populations on genetic, I think the results maybe greater than 1. In human, if the outgroup is chimpanzee, the results maybe greater than 1.  Is this right?

Best
Zhuqing

**Comment by hssKK** [comment]
Dear @bumblenick
here is my result:
Source 1             Source 2               Target           f_3       std. err           Z    SNPs
Ancient                  groupA             Outgroup      1.196981       0.005023     238.302 3926773
Ancient                  groupB             Outgroup      1.224042       0.005237     233.734 6541385
Ancient                  groupC             Outgroup      1.247120       0.005399     230.995 5615777
Ancient                  groupD             Outgroup      1.228669       0.005196     236.460 5276082
Ancient                  groupE             Outgroup      1.200275       0.005038     238.225 6352217
Ancient                  groupF             Outgroup      1.211333       0.005147     235.364 6104010
Ancient                  groupG             Outgroup      1.217125       0.005233     232.604 5978688
Ancient                  groupH             Outgroup      1.157842       0.004940     234.362 5602913
Is that mean my Ancient sample is most close to groupC ?
The results is greater than 1,does it may have some effect ?
What's more,because of the low coverage (1.1X ),heterozygosity is hard obtained from genotype calls ,does it may have some effect ?
I’m looking forward to your reply.
Thanks!

**Comment by bumblenick** [comment]
You can't use f3 on a single sample unless you have good diploid calls
which
requires about 20X coverage.  I wouldn't trust these results at all.

N

**Comment by hssKK** [comment]
Dear @bumblenick 
It's hard for me to have an ancient sample which have coverage more than 20X . I also have two ancient sample ( mean coverage1.5X ) , if I take they as a population , is that enough ?
Or can I use D-statistic D(outgroup,ancient;A,B) to decide whilch group my ancient sample most close to ?
Or can you give my some suggestion on this problem?
Thanks a lot !

**Comment by bumblenick** [comment]
With 2 samples you can use f3 (qp3Pop, inbreed: YES)

N

**Comment by hssKK** [comment]
Thank you very much !
