### ISSUE TITLE
D-statistics used in small number of SNPs

### ISSUE THREAD

**Issue by silvewheat** [DReichLab/AdmixTools#22]
Hello,
          I use D-statistics in one thousand SNP, and the result is all zero.  Why is it happened? The number of snp is too small? Can it been solved?

**Comment by bumblenick** [comment]
Two possibilities.
1) None of your snps are polymorphic or have valid data.  The output log
file will tell you that.
2) There are no ABBA/BABA events in your dataset.   If your files are in
eigenstrat format
you can check that yourself.

Nick

**Comment by silvewheat** [comment]
The log file say:

snps: 1225  indivs: 11
number of blocks for jackknife: 1
nrows, ncols: 11 1225

So, Is it mean the dataset is ok, and it just have no ABBA/BABA events?

Thanks!
