### ISSUE TITLE
qpAdm sometimes copies admixture proportions in other lines

### ISSUE THREAD

**Issue by TCLamnidis** [DReichLab/AdmixTools#24]
Hello!

Sometimes qpAdm will give me identical admixture proportions between different models, and even forego forcing some to 0. (see part of results below). 
I am fairly sure the chi square statistics are accurate for the model, I just don't get the admixture proportions.

    fixed pat  wt  dof     chisq       tail prob
        00000  0     4     2.925        0.570392     0.006    -0.022     0.557     0.048     0.411  infeasible
        00001  1     5   101.589     2.44391e-20    -4.084     0.558     0.092     4.434     0.000  infeasible
        00010  1     5     3.026        0.696022    -4.084     0.558     0.092     4.434     0.000  infeasible
        00100  1     5    83.532     1.52896e-16    -4.084     0.558     0.092     4.434     0.000  infeasible

Clearly in the latter 2 models, the final component shouldn't be forced to 0, and instead the other components should.

Is this a problem with my use, or an internal problem?
Cheers

**Comment by TCLamnidis** [comment]
I should add, as far as I can see, this happens consistently with certain sample sets, copying over the same models every time (at least in my 3 replicates).

**Comment by bumblenick** [comment]
This does look like a bug.  Does it ever happen when the model is
"feasible"

A workaround of course is to rerun deleting sources you don't want, and
rerun.  Please tell me the version number
(grep on version: in logfile)

N

**Comment by TCLamnidis** [comment]
```## qpAdm version: 610```

Yes, it also happens with feasible models:
```    fixed pat  wt  dof     chisq       tail prob
        00000  0     2     4.803       0.0905804     0.592     0.097     0.183     0.101     0.028 
        00001  1     3    17.570     0.000539394     0.493     0.098     0.210     0.199     0.000 
        00010  1     3     7.677       0.0531877     0.493     0.098     0.210     0.199     0.000 
```
And it seems to overwrite models that are not rejected too, since in the first example one of the models had a high tail probability.

**Comment by bumblenick** [comment]
I think I found the problem and am in the process of fixing.  It likely is
caused by having 2 populations in
the left set that are very very similar genetically.  Is that plausible
here?

Nick

**Comment by TCLamnidis** [comment]
Here, the five source left populations are genetically distinct. Moreover, they remain mostly intact across multiple analyses, the changing variable being the population being explained as a 5-way mixture. Only specific target populations seem to trigger this effect, while most run normally without copied lines in the outputs. 

Note: I have managed to run the reduced models without problem, as you suggested.

**Comment by bumblenick** [comment]
I just pushed a new version of Admixtools to github.  Probably this fixes
your problem.  Please let me know!

Nick

**Comment by TCLamnidis** [comment]
I tried rerunning some of the models that had problems before, and all mixture proportions are printed normally now.

**Comment by bumblenick** [comment]
Great; I think you have a boundary case in which some populations have very
thin data.
In the new release I trap these cases and do something (fairly) reasonable.

Nick
