### ISSUE TITLE
how to explain the D-stastics result 

### ISSUE THREAD

**Issue by XuexueLiu** [DReichLab/AdmixTools#26]
Dear  @bumblenick
in D-stastics README file,  what's the meaning of "If the Z-score is +ve, then the gene flow occured either between W and Y or X and Z 
If the Z-score is -ve, then the gene flow occured either between W and Z or X and Y." 
and I got the result : W X Y Z  0.0027(Dstat)     1.496337525(Z score) 335725(BABA) 7196699(ABBA), so  W and Y or X and Z had gene flow?  thankyou

**Comment by bumblenick** [comment]
Please tell me the version # of qpDstat.  It looks like you have run into a
formatting bug with
the BABA count merging with Z.  If your version is current I'll fix
quickly,
But this is a Z score of  1.496, not significant with flow W <-> Y or X <->
Z

Nick

**Comment by bumblenick** [comment]
There was a formatting issue in qpDstat, now I hope fixed.

Nick

**Comment by XuexueLiu** [comment]
Dear Nick
 I used the ## qpDstat version: 662  thankyou!

**Comment by bumblenick** [comment]
Latest version should fix the formatting problem.  You are likely using a
dataset with a very large # of SNPs.  You
should consider thinning it.

N
