### ISSUE TITLE
Example data directory

### ISSUE THREAD

**Issue by biologyguy** [DReichLab/AdmixTools#3]
Hi there,
Would it be possible to get the AdmixTools/data/ directory uploaded to the git repo? The log files in AdmixTools/examples/ are referencing ../data/allmap, and it would be very useful to be able to see the input files and run the examples for troubleshooting purposes.
Thanks!
-Steve

**Comment by bumblenick** [comment]
Dear Steve:
  We are short of bioinformatics support, and think we will be shortly
removing Admixtools from github.  I'm sad about this...

Nick

**Comment by biologyguy** [comment]
Thanks for letting me know Nick, and I'm sorry to hear about the shortage of support for your project. I really hope you will choose to leave the GitHub repo available though, as it gives the community an easy way to access the software. Maybe just put a disclaimer in the readme that active development has been suspended?

**Comment by mathii** [comment]
Dear Steve, 

You can now download the data files from https://genetics.med.harvard.edu/reich/Reich_Lab/Software_files/AdmixTools_Example_Data.tar.gz

- Iain

**Comment by biologyguy** [comment]
That's awesome, thanks Iain.
I see you've included a note in the README as well, so I think we can close this issue out.
Best,
-Steve
