### ISSUE TITLE
mac install issue

### ISSUE THREAD

**Issue by vvv214** [DReichLab/AdmixTools#31]
I have problem installing the software with the following environment:
macOS 10.12.6
openblas 0.2.20
/usr/local/Cellar/gsl/2.4
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)

Error message:
cc -L./nicksrc -L/usr/local/opt/openblas/lib -L/usr/local/opt/gsl/lib  qpff3base.o nicksrc/libnick.a qpgsubs.o qpsubs.o mcio.o admutils.o egsubs.o regsubs.o ldsubs.o  -lgsl -lopenblas -lm -lnick -o qpff3base
cc -c -g -p -Wimplicit -I./ -I./nicksrc -I/usr/local/opt/openblas/include -I/usr/local/opt/gsl/include   -c -o rolloffp.o rolloffp.c
clang: warning: argument unused during compilation: '-p' [-Wunused-command-line-argument]
rolloffp.c:789:23: error: non-void function 'cntit1' should return a value [-Wreturn-type]
  if (cupt -> ignore) return ;
                      ^
rolloffp.c:808:23: error: non-void function 'cntit2' should return a value [-Wreturn-type]
  if (cupt -> ignore) return ;
                      ^
rolloffp.c:809:24: error: non-void function 'cntit2' should return a value [-Wreturn-type]
  if (cupt2 -> ignore) return ;
                       ^
3 errors generated.
make: *** [rolloffp.o] Error 1

**Comment by MatthewMah** [comment]
@vvv214 The fix noted above should resolve this issue. Please update and try rebuilding.
