### ISSUE TITLE
qp3pop // warning: dubious parameter

### ISSUE THREAD

**Issue by kafka2184** [DReichLab/AdmixTools#33]
Hello,
I've got a problem in my parameter, in the log output file it begin by "_warning: dubious parameter_"
I can't find where is the problem. I got the result at the end for qp3pop, but don't know if it's serious problem this warning.
Maybe someone can help....

**the parfile** : 
parameter file: parqp3
DIR: /home/mferrand/
SSS: ALL
genotypename: /home/mferrand/ALL.geno
snpname: /home/mferrand/ALL.snp
indivname: /home/mferrand/ALL.ind
popfilename:  /home/mferrand/list_qp3test.txt

I have my 3 files in the good format (I hope)
ALL.geno
1000000
1000000
0001000
etc... 

ALL.snp
N-0001 1 0.31  10015031
N-0002 1 0.31  10039272
N-0003 1 0.31  10048150
etc...

ALL.ind
"N9"	"0" "N9"
"N5" "0" "N5"
"D1"	"0" "D1"
"T1"	"0" "T1"
"D22" "0"	"D22"
"N1"	"0" "N1"
"Col0" "0"	"Col0"

**the popfilename: **  list_qp3test.txt : 
"T1" "N1" "D1"	
"D22" "N9" "D1"	
"N1"	"N9"	"D1"	
etc...

**then the logfile give = ** 
parameter file: parqp3.txt
**warning: dubious parameter, please check the parameter name parameter
THE INPUT PARAMETERS
PARAMETER NAME: VALUE
parameter file: parqp3Pop
DIR: /home/mferrand/
SSS: ALL
genotypename: /home/mferrand/ALL.geno
snpname: /home/mferrand/ALL.snp
indivname: /home/mferrand/ALL.ind
popfilename: /home/mferrand/list_qp3test.txt
qp3Pop version: 204
nplist: 56
number of blocks for block jackknife: 68
snps: 54984    
                      Source 1             Source 2               Target           f_3       std. err           Z    SNPs
 result:                  "T1"                 "N1"                 "D1"     -0.196412       0.015795     -12.435   29533
 result:                 "D22"                 "N9"                 "D1"     -0.234678       0.008221     -28.547   26423
 result:                  "N1"                 "N9"                 "D1"     -0.196241       0.018510     -10.602   29550
Etc...

Thanks in advance !

**Comment by bumblenick** [comment]
It does no real harm but your top line starting parameter... should not be
there

N

**Comment by kafka2184** [comment]
ok thanks !
