### ISSUE TITLE
please release executable files

### ISSUE THREAD

**Issue by JPingAMMS** [DReichLab/AdmixTools#43]
Note that v5.0 release. Great!

However, it is really hard to compile at a no-root-privilege server or a no-web server. Executable files may get more users.

**Comment by MatthewMah** [comment]
I'm sorry, we do not have the resources to build and maintain executables for multiple platforms. Binaries are not really portable; they depend upon libraries that vary across distributions. 

I actually build AdmixTools on a server where I do not have root access. I do have support from the administrators to have the lapack, openblas, and gsl dependencies installed.
