### ISSUE TITLE
Ubuntu installation error and solution

### ISSUE THREAD

**Issue by owensgl** [DReichLab/AdmixTools#48]
I was trying to install v5.1 on a ubuntu system and I kept getting this error:

> cc -L./nicksrc  qpAdm.o nicksrc/libnick.a qpsubs.o mcio.o ldsubs.o admutils.o egsubs.o regsubs.o f4rank.o eigsubs.o eigx.o  -lgsl -lopenblas -lm -lnick -o qpAdm
> eigx.o: In function `eigx_':
> /home/owens/bin/AdmixTools-5.1/src/eigx.c:94: undefined reference to `dspev_'
> eigx.o: In function `eigxv_':
> /home/owens/bin/AdmixTools-5.1/src/eigx.c:118: undefined reference to `dspev_'
> eigx.o: In function `cdc_':
> /home/owens/bin/AdmixTools-5.1/src/eigx.c:136: undefined reference to `dpotrf_'
> eigx.o: In function `inverse_':
> /home/owens/bin/AdmixTools-5.1/src/eigx.c:173: undefined reference to `dgetrf_'
> /home/owens/bin/AdmixTools-5.1/src/eigx.c:180: undefined reference to `dgetri_'
> eigx.o: In function `solve_':
> /home/owens/bin/AdmixTools-5.1/src/eigx.c:206: undefined reference to `dgetrf_'
> /home/owens/bin/AdmixTools-5.1/src/eigx.c:212: undefined reference to `dgetrs_'
> eigx.o: In function `geneigsolve_':
> /home/owens/bin/AdmixTools-5.1/src/eigx.c:230: undefined reference to `dsygv_'
> collect2: error: ld returned 1 exit status

This happened despite installing and updating GSL, openblas, gfortran, and lapack.
Based on this post about a related program (https://github.com/DReichLab/EIG/issues/8) I tried 
`make all LDLIBS="-llapack"`
This seemed to fix the error, and it installed fine. 

Including a note about this might be useful in the install readme, and I'm posting this issue to help anyone else with the same issue.

**Comment by MatthewMah** [comment]
Thanks for your note. We actually were not sure what platform(s) needed the additional flag. I will add a note to the readme.

**Comment by MatthewMah** [comment]
README note finally added in 24e63b568ef78ec89869544a6761e31bcaa5bc49.
