### ISSUE TITLE
Haploid setting?

### ISSUE THREAD

**Issue by DinRigtigeFar** [DReichLab/AdmixTools#50]
Hi
Is it possible to run qpGraph with a haploid setting? I can see a reference to "haploid" in the qpGraph.c file (on line 1774). Is it as simple as to change the 0 to a 1?

Thanks in advance

**Comment by bumblenick** [comment]
1) Code
inbreed: YES
2) Data should be pseudo-haploid -- 0 and 2 counts.

I will update the documentation shortly.

Nick

**Comment by DinRigtigeFar** [comment]
Thanks for the quick reply.
