### ISSUE TITLE
Does three population test can provide the direction of gene flow?

### ISSUE THREAD

**Issue by biozzq** [DReichLab/AdmixTools#58]
Dear @bumblenick ,

In your 2012 paper, you found that the gene flow from northern Europeangene into Spain by three population test. I can not understand how did you know the direction?

Best regards,
Zhuqing

**Comment by bumblenick** [comment]
The 3 population test is a test precisely that the target population (in
this case Spain) is admixed.
 very negative f3 thus shows the direction of flow.

Nick

**Comment by biozzq** [comment]
Dear @bumblenick,

Thank you very much.

Best regards,
Zhuqing
