### ISSUE TITLE
Release archive 6.0 does not build convertf, mergeit nor rollof

### ISSUE THREAD

**Issue by EricDeveaud** [DReichLab/AdmixTools#65]
Hello has already mentioned in #45 

release archive-6.0 https://github.com/DReichLab/AdmixTools/archive/v6.0.tar.gz does not build convertf , mergit and also rollof
build of convertf and mergeit was fixed on https://github.com/DReichLab/AdmixTools/commit/213ceff8f2bf4cde6fdfe304b622ff0f2ef778ae and broken back again on https://github.com/DReichLab/AdmixTools/commit/762d30c737c4793678d7f3470f6e1c1c0667d884

convertf and rollof are mentioned on the readme.

```
The package contains 6 programs: 
convertf: See README.CONVERTF for documentation of programs for converting file formats.

SNIP....

rolloff:  See README.ROLLOFF/ README.ROLLOFF_OUTPUT for details for running rolloff. This program can be used for dating admixture events.
```
regards

Eric

**Comment by MatthewMah** [comment]
This should be fixed in 24e63b568ef78ec89869544a6761e31bcaa5bc49.
