### ISSUE TITLE
AABB/BBAA sites

### ISSUE THREAD

**Issue by qhelleu** [DReichLab/AdmixTools#68]
Hi,
The number of AABB/BBAA sites is a great source of information, and helps to filter the results obtained with qpDstat (e.g. to keep only BBAA>ABBA>BABA comparisons). Even if we can 'guess' them by running all possible combination, it would be easier to obtain them directly. Would it be possible that qpDstat gives also the number of AABB/BBAA sites for each comparison?
Thanks,
Best.

**Comment by bumblenick** [comment]
I don't use the BBAA + AABB counts much.  But note that if you run qpDstat
with 2 input lines in popfilename:

W X Y Z
W Y X Z   BABA here is BBAA on top line

I would rather do it this way than add to the output on the log file

Nick
