### ISSUE TITLE
Killed error on qpdstat

### ISSUE THREAD

**Issue by geneanalyst** [DReichLab/AdmixTools#70]
I have been using Admixtools for the past 5 years with no issues. I do have a powerful 8 thread Linux platform. 

To mitigate ascertainment bias I just increased from 1.2M Snps to 4M Snps. However I now receive a killed error with no further explanation when running qpdstat. I suspect it's related to CPU load because when I decrease my pop list down to 1 line the error disappears. I don't use ALLSNPs to limit to intersecting SNPs on all pops.

Is there a maximum number of SNPs/line combinations we need to be aware of?

Also do any of the programs within Admixtools support 8 threads ? If so which ones and what flag do we use.

Thanks

**Comment by bumblenick** [comment]
I suspect that this is a system error and you exceeded the memory limit.
smartpca supports multithreads but ADMIXTOOLS doesn't.  For qpDstat this
seems
hardly necessary as processing the individual f_4 stats is embarrassingly
parallel.

Nick

**Comment by geneanalyst** [comment]
Thanks, understood. Any workarounds by using various commands within the parfile or code modification you can think of besides reducing the number of lines in popfilenames ( I did build a dstat.sh (shell script)  to run in batches but updating all those lists used by popfilenames is time consuming)

**Comment by bumblenick** [comment]
I do the following
1) Use popfilename: <list of quadruples>
Now
2)
qpDstat -p <parfile> -l <lo> -h <hi>  where lo and hi are line numbers in
the list makes
it easy to parallel process.  I typlcally set hi to lo+24 and do batches of
25 stats at a time.

**Comment by geneanalyst** [comment]
Ok thanks for the help. Nothing corrupted with the individual pops. It turned out to be overload. I will change the command as per your suggestion. TCR

**Comment by bumblenick** [comment]
If you email me directly I can send you a little Perl script I use to do this job

Nick

**Comment by geneanalyst** [comment]
Just emailed you.
