### ISSUE TITLE
Feature suggestion (qpGraph): make labels available in .log file

### ISSUE THREAD

**Issue by TobiasGold** [DReichLab/AdmixTools#71]
Dear Nick and contributors,

I am currently running quite a few qpGraphs to fine-tune my topology. To do this task more intelligently I want to look at the log file of the run and see which (outlier) statistics were produced. 
While I can read the fst, f2, etc statistics, since the populations are in order I specified them in the S1 ("design") file, this does not work for the outlier f4 statistics. I have some populations which start with the same prefix (eg. "HGDP_abc") which I can't distinguish because they are all labeled "HGD". 

My suggestion would be to use the first three letters of the label which I specify in the S1 file. Since I specify labels I am quite aware of those, so I think I (or any other user) would not be surprised to find those labels again in the log file. 
Furthermore, this possibility could be toggled using an option, like "uselabelsinlog: YES" (default: NO)
Also I think those three-letter labels could be used in the fst, f2, etc. statistics, they would not shift the tables there. 

I am aware that I could rename my populations in the file, but I feel most of the time people who use qpGraph usually use many different programmes as well. For my workflow it is easier to have one (quite) steady file with the same names (which also other colleagues use...). So, I would prefer to change behaviour like this in the programme itself.

Best,
Tobias

**Comment by bumblenick** [comment]
I want to support reasonable requests and see that you have a difficulty.
Your suggestion of just
using 3 letters of the labels is a bit funky though.   Suppose I had an
option to publish the full name in
the outlier output.    That might make long lines if you use very long
labels (which may be a bad idea)
but would that help you?

Probably best to reply to <nickp@broadinstitute.org> as this thread is a
bit specialized.

Nick

**Comment by TobiasGold** [comment]
This Problem is solved by adding the line "fulloutlier: YES" in the parameter file!
Then the outlier statistics have full names. 
Thanks for the solution @bumblenick !
