### ISSUE TITLE
Do any of the tools require genetic map distances for accuracy

### ISSUE THREAD

**Issue by geneanalyst** [DReichLab/AdmixTools#73]
When Plink data is converted to Eigenstrat the genetic map distances are not added to column 3 of the .snp file. In other words column 3 of the .snp file has zeros.

Do any of the codes within Admixtools (F2s, qpAdm, qpdstat, etc ) rely on genetic map distances for accuracy ?

 If so I can add them to column 3 of .snp from my Hapmap B37 recombination rate reference

**Comment by bumblenick** [comment]
You should use genetic map if possible;  ROLLOFF and DATES which are
strictly outside ADMIXTOOLS really require it.

I will look into the map conversion from PLINK.

Nick

**Comment by geneanalyst** [comment]
Are F2s or F3s or qpAdm affected if genetic map is missing from .snp ?

FYI, Plink messes the order of the reference and alternate allele. I've noticed that within .snp column 5 is for REF and column 6 for ALT. However conversions from Plink map often result in REF being placed in col 6 of .snp and ALT in col 5.

Although I'm not sure whether that affects MAF calculations within Admixtools, I have taken the precaution of correcting the misplaced placement of REF into column 6 of .snp using my Hg19 reference genome. 

Additionally, I commonly see "X" placed into column 6 of .snp (ALT column) in conversions from Plink map. I have no idea what "X" stands for

**Comment by bumblenick** [comment]
1) f-stats are not affected by the map but std, errors and Z scores are
2) X means that the alternate allele is unknown.

N

**Comment by geneanalyst** [comment]
Thanks!

2- I've been replacing "X' with ALT from my Hg19 reference genome.
