### ISSUE TITLE
qpDstat not using numchrom from parameter file

### ISSUE THREAD

**Issue by jooppenh** [DReichLab/AdmixTools#78]
Dear Nick,

I think that qpDstat (version 970) does not make use of the numchrom option defined in the parameter file, and so will always default to the global value of 22. It seems to me that numchrom is never set when reading from the par file in qpDstat.c, as it is in eg. qp3Pop.c, though the value in the par file is reported.

Would it be possible to add this option for qpDstat?

Thanks,
Jonas

**Comment by bumblenick** [comment]
You are right!  I guess bitrot...
will be fixed very soon

N

**Comment by jooppenh** [comment]
Yes, looks like it was lost in the upgrade to Admixtools v7.0. Thanks!

Best,
Jonas
