### ISSUE TITLE
qpadm with single sample - is it possible to run?

### ISSUE THREAD

**Issue by eshab5** [DReichLab/AdmixTools#86]
Hello Dr.Patterson,

I am trying to run qpadm on a single ancient sample (that is pseudohaploid). I am using that as my target.

My .par file looks like this:
genotypename: file.geno
snpname: file.snp 
indivname: file.ind
popleft: left.pops
popright:  right.pops
allsnps: YES
details: YES
inbreed : YES
oldallsnpsmode: NO

My left and right population files, have one population per line

When I submit this par file for the run, I am getting:

fatalx:
pop: SampleA has sample size 1 and inbreed set
sh: line 1: 96340 Aborted                 qpfstats -p /tmp/ppp.96308 > /tmp/fslog.96308
/var/spool/torque/mom_priv/jobs/31750267.cri16sc001.SC: line 16: 96308 Segmentation fault 

Therefore, I wanted to kindly know if it is possible to run qpadm on a single sample taken as a target?

Thanking You,
Esha

**Comment by bumblenick** [comment]
Dear Esha
 qpAdm only uses f4 stats;
Code inbreed: NO
(although this is kinda a lie)
and all should be well.

Nick



Nick

**Comment by eshab5** [comment]
Dear Dr.Patterson,

It worked! Thank you so much.


Sincerely,
Esha
