### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by llq0325** [DReichLab/AdmixTools#9]
Hi all,
I got problems during compiling. Anyone know how to solve this problem? 

liu194@DeepPhylo:~/AdmixTools/src$ make all
mkdir -p  /home/liu194/AdmixTools/src/admixlib
mkdir -p  /home/liu194/AdmixTools/src/admixtables
mkdir -p  /home/liu194/AdmixTools/src/admixinclude
mkdir -p  /home/liu194/AdmixTools/src/../bin
cp  *.h  /home/liu194/AdmixTools/src/admixinclude  
cp  nicksrc/*.h  /home/liu194/AdmixTools/src/admixinclude  
ar -r libnick.a strsubs.o sortit.o vsubs.o statsubs.o linsubs.o getpars.o xsearch.o gauss.o	gds.o
ranlib libnick.a
cp libnick.a  /home/liu194/AdmixTools/src/admixlib/nicklib.a
gcc -I/home/liu194/AdmixTools/src/admixinclude   -g  -lm  -o qp3Pop  qp3Pop.o qpsubs.o mcio.o ldsubs.o admutils.o  egsubs.o regsubs.o /home/liu194/AdmixTools/src/admixlib/nicklib.a
qpsubs.o: In function `getpdata':
/home/liu194/AdmixTools/src/qpsubs.c:143: undefined reference to `sqrt'
qpsubs.o: In function `getcolx':
/home/liu194/AdmixTools/src/qpsubs.c:336: undefined reference to `sqrt'
qpsubs.o: In function `dofancy':
/home/liu194/AdmixTools/src/qpsubs.c:401: undefined reference to `sqrt'
qpsubs.o: In function `yll':
/home/liu194/AdmixTools/src/qpsubs.c:450: undefined reference to `log'
qpsubs.o: In function `ridoutlier':
/home/liu194/AdmixTools/src/qpsubs.c:713: undefined reference to `sqrt'
qpsubs.o: In function `crho':
/home/liu194/AdmixTools/src/qpsubs.c:1683: undefined reference to `sqrt'
qpsubs.o: In function `wjackestx':
/home/liu194/AdmixTools/src/qpsubs.c:2709: undefined reference to `sqrt'
qpsubs.o: In function `wjackvestx':
/home/liu194/AdmixTools/src/qpsubs.c:3216: undefined reference to `sqrt'
qpsubs.o: In function `printnorm':
/home/liu194/AdmixTools/src/qpsubs.c:3618: undefined reference to `sqrt'
mcio.o: In function `nextmesh':
/home/liu194/AdmixTools/src/mcio.c:701: undefined reference to `ceil'
mcio.o: In function `getgenos':
/home/liu194/AdmixTools/src/mcio.c:1439: undefined reference to `ceil'
mcio.o: In function `outpack':
/home/liu194/AdmixTools/src/mcio.c:2336: undefined reference to `ceil'
mcio.o: In function `ineigenstrat':
/home/liu194/AdmixTools/src/mcio.c:2494: undefined reference to `ceil'
mcio.o: In function `inpack':
/home/liu194/AdmixTools/src/mcio.c:2727: undefined reference to `ceil'
mcio.o:/home/liu194/AdmixTools/src/mcio.c:3298: more undefined references to `ceil' follow
mcio.o: In function `killhir2':
/home/liu194/AdmixTools/src/mcio.c:4175: undefined reference to `sqrt'
mcio.o: In function `inpack2':
/home/liu194/AdmixTools/src/mcio.c:4335: undefined reference to `ceil'
mcio.o: In function `genoopenit':
/home/liu194/AdmixTools/src/mcio.c:4689: undefined reference to `ceil'
ldsubs.o: In function `zdip0':
/home/liu194/AdmixTools/src/ldsubs.c:488: undefined reference to `sqrt'
ldsubs.o: In function `calccorr':
/home/liu194/AdmixTools/src/ldsubs.c:574: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/ldsubs.c:575: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/ldsubs.c:585: undefined reference to `log'
/home/liu194/AdmixTools/src/ldsubs.c:586: undefined reference to `sqrt'
admutils.o: In function `xxlog2':
/home/liu194/AdmixTools/src/admutils.c:527: undefined reference to `log'
admutils.o: In function `kurtosis':
/home/liu194/AdmixTools/src/admutils.c:1020: undefined reference to `sqrt'
regsubs.o: In function `regressit':
/home/liu194/AdmixTools/src/regsubs.c:73: undefined reference to `log'
regsubs.o: In function `regressitall':
/home/liu194/AdmixTools/src/regsubs.c:86: undefined reference to `pow'
regsubs.o: In function `calcgh':
/home/liu194/AdmixTools/src/regsubs.c:338: undefined reference to `sqrt'
regsubs.o: In function `zlike':
/home/liu194/AdmixTools/src/regsubs.c:368: undefined reference to `log'
/home/liu194/AdmixTools/src/regsubs.c:368: undefined reference to `log'
regsubs.o: In function `hgrad':
/home/liu194/AdmixTools/src/regsubs.c:618: undefined reference to `pow'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `vsqrt':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:75: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `vlog':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:106: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `vexp':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:126: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `corr':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:427: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `corrx':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:456: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `nnint':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:780: undefined reference to `lrint'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `rndit':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1244: undefined reference to `nearbyint'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `NPlog2':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1352: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `logfac':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1364: undefined reference to `lgamma'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `log2fac':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1418: undefined reference to `lgamma'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `addlog':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1441: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1442: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `ipow2':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1476: undefined reference to `pow'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `pow10':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1482: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `vpow10':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1491: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `vlog10':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1499: undefined reference to `log10'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `hlife':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:1934: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(vsubs.o): In function `isprime':
/home/liu194/AdmixTools/src/nicksrc/vsubs.c:2222: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `nordis':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:57: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:58: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `ntail':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:86: undefined reference to `erfc'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:92: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:93: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `zzprob':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:113: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:113: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:116: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:119: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `medchi':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:175: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `ks2':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:245: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `probks':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:273: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `conchiv':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:323: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `z2x2':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:373: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `zprob':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:494: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `setzptable':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:530: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `znewt':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:551: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:551: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `mleg':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:609: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:617: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:627: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:637: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `psi':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:662: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o):/home/liu194/AdmixTools/src/nicksrc/statsubs.c:725: more undefined references to `log' follow
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `bessi1':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:781: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:781: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `logbessi0':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:807: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:821: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:823: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `bessi0':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:862: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:862: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `li2':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:916: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:916: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `hwstat':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:962: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `bprob':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:978: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:978: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `gammprob':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:993: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:994: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `binlogtail':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1078: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o):/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1134: more undefined references to `log' follow
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `xlgamma':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1168: undefined reference to `lgamma'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1173: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1174: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `rtlchsq':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1194: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1196: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `pochisq':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1233: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1234: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1242: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1245: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1246: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1253: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `critchi':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1289: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1293: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `pof':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1346: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1349: undefined reference to `atan'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1353: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1358: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `ltlg1':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1446: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1447: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1449: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `rtlg2':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1486: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1487: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1489: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `twdensx':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1543: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1544: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1545: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1547: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `twtailx':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1559: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1560: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1561: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1563: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `twnorm':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1597: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1597: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1599: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1599: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1600: undefined reference to `pow'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `dirmult':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1853: undefined reference to `lgamma'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1854: undefined reference to `lgamma'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1856: undefined reference to `lgamma'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1857: undefined reference to `lgamma'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `betai':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1898: undefined reference to `lgamma'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o):/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1898: more undefined references to `lgamma' follow
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `betai':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1898: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1899: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:1897: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `weightjackx':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:2172: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `calcfc':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:2232: undefined reference to `cos'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:2233: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:2243: undefined reference to `cos'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `setbino':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:2307: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `dither':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:2362: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(statsubs.o): In function `exx':
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:2408: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/statsubs.c:2412: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(linsubs.o): In function `bal':
/home/liu194/AdmixTools/src/nicksrc/linsubs.c:32: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(linsubs.o): In function `choldc':
/home/liu194/AdmixTools/src/nicksrc/linsubs.c:276: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(gauss.o): In function `gauss':
/home/liu194/AdmixTools/src/nicksrc/gauss.c:26: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/gauss.c:26: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(gds.o): In function `randev1':
/home/liu194/AdmixTools/src/nicksrc/gds.c:42: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/gds.c:49: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/gds.c:49: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(gds.o): In function `randev0':
/home/liu194/AdmixTools/src/nicksrc/gds.c:65: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/gds.c:70: undefined reference to `pow'
/home/liu194/AdmixTools/src/nicksrc/gds.c:74: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/gds.c:75: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/gds.c:81: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(gds.o): In function `ranexp':
/home/liu194/AdmixTools/src/nicksrc/gds.c:101: undefined reference to `log'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(gds.o): In function `poidev':
/home/liu194/AdmixTools/src/nicksrc/gds.c:164: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/gds.c:176: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/gds.c:177: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/gds.c:178: undefined reference to `lgamma'
/home/liu194/AdmixTools/src/nicksrc/gds.c:182: undefined reference to `tan'
/home/liu194/AdmixTools/src/nicksrc/gds.c:185: undefined reference to `floor'
/home/liu194/AdmixTools/src/nicksrc/gds.c:186: undefined reference to `lgamma'
/home/liu194/AdmixTools/src/nicksrc/gds.c:186: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(gds.o): In function `ranpoiss1':
/home/liu194/AdmixTools/src/nicksrc/gds.c:432: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(gds.o): In function `raninvwis':
/home/liu194/AdmixTools/src/nicksrc/gds.c:557: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/gds.c:565: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(gds.o): In function `rant':
/home/liu194/AdmixTools/src/nicksrc/gds.c:680: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/nicksrc/gds.c:684: undefined reference to `sqrt'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(gds.o): In function `samppow':
/home/liu194/AdmixTools/src/nicksrc/gds.c:710: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/gds.c:710: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/gds.c:714: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/gds.c:714: undefined reference to `log'
/home/liu194/AdmixTools/src/nicksrc/gds.c:724: undefined reference to `exp'
/home/liu194/AdmixTools/src/admixlib/nicklib.a(gds.o): In function `ranhprob':
/home/liu194/AdmixTools/src/nicksrc/gds.c:821: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/gds.c:838: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/gds.c:839: undefined reference to `exp'
/home/liu194/AdmixTools/src/nicksrc/gds.c:839: undefined reference to `exp'
collect2: ld returned 1 exit status
make: *** [qp3Pop] Error 1

**Comment by shubhamsaini** [comment]
This is due to the recent changes to the gcc compiler. The flags, and their usage has changed. Try my makefile:
http://pastebin.com/Fpjwzczh

**Comment by francescomontinaro** [comment]
Hi,
This did not work for me. The compiled executables had a wrong behaviour.

**Comment by XuexueLiu** [comment]
I also used this new Makefile, but got the result:
/usr/bin/ld: cannot find -lopenblas
collect2: ld returned 1 exit status
make: *** [qpAdm] Error 1
how should I deal with this problem, thankyou!

**Comment by MatthewMah** [comment]
@XuexueLiu This means the linker cannot find the required openblas library. You resolve this by adding the linker option to inform of the location of the library, which must be installed somewhere. 

For example, if the library is located in the directory `/n/app/openblas/0.2.19/lib` add the gcc option
`-L/n/app/openblas/0.2.19/lib`

**Comment by geneanalyst** [comment]
I also used this Makefile, but got the following error:

In file included from qpAdm.c:4:0:
qpAdm.c: In function ‘calcevar’:
qpAdm.c:1041:5: **error**: expected ‘(’ before ‘__builtin_isnan’
  if isnan(y) { 
     ^
qpAdm.c: In function ‘scorel’:
qpAdm.c:1140:1: **warning**: implicit declaration of function ‘eigvecs’ [-Wimplicit-function-declaration]
 eigvecs(V, evals, evecs, n) ; 
 ^
<builtin>: recipe for target 'qpAdm.o' failed
make: *** [qpAdm.o] Error 1


I looked in qpAdm.c and checked line 1041. This is what is there:

ZALLOC (wjack, nblocks, double);
for (k = 0; k < nblocks; ++k) {
wjack[k] = asum (bbot[k], dim);
 y = asum(tmean[k], nl) ; 
 **if isnan(y) {** 
  copyarr(totmean, tmean[k], nl) ; 
  wjack[k] = 0 ;
 }

}

Thanks in advance.

**Comment by bumblenick** [comment]
I fixed this (I hope).   My compiler is more tolerant of sloppy code than
yours!

 Nick

**Comment by geneanalyst** [comment]
Thanks bumblenick! Will you be updating the Makefile in AdmixTools at Reichlab?

**Comment by bumblenick** [comment]
That's complicated.  I'm learning that it's hard to produce a universal
Makefile.   We should improve the README
to give better install instructions.

Nick

**Comment by geneanalyst** [comment]
What about source files such as qpAdm.c. Will those be updated?

**Comment by bumblenick** [comment]
Yes. We will do that

N

**Comment by MatthewMah** [comment]
I have resolved the original Makefile issue here in caef66e2e252cb4b7f0f15e6a68fa300ebba8fa9.

**Comment by RCWilliams** [comment]
I'm sorry I know this is closed, but I just installed AdmixTools (including the new Makefile) and I'm still getting the same error:

...
collect2: error: ld returned 1 exit status
make: *** [qp3Pop] Error 1

Any suggestions?

**Comment by MatthewMah** [comment]
@RCWilliams The messages that come before the ld error matter. If yours do not match those above, please open a new issue.
