### ISSUE TITLE
Nothing happens when using convertf for PACKEDPED to PACKEDANCESTRYMAP 

### ISSUE THREAD

**Issue by vsds92** [DReichLab/AdmixTools#99]
I have used convertf for converting from PACKEDANCESTRYMAP to PACKEDPED and it works just fine. But when I try the opposite, then nothing happens - you can see an attached screenshot. 
![Capture_convertf](https://user-images.githubusercontent.com/121052635/208489344-c66da14b-c1bb-4609-aa28-f313fc288a3e.PNG)

**Comment by bumblenick** [comment]
Does this mean the problem is now solved?

Nick

**Comment by vsds92** [comment]
Yes Nick. For 3 hrs nothing happened and then it started converting the 1240k database. The whole thing took many hours but worked in the end . Thank you
